### ISSUE TITLE
not working  (output data not  showing) 

### ISSUE THREAD

**Issue by appasaheb4** [ChrisDowney1996/react-native-barcode-scanners#2]
<img width="1103" alt="screenshot 2019-02-27 at 3 33 28 pm" src="https://user-images.githubusercontent.com/24726539/53482376-15b97000-3aa5-11e9-8ea7-5104847c30d9.png">

openGallery() {
    const _this = this
    const photoOptions = {
      storageOptions: {
        skipBackup: true,
        path: 'images'
      }
    }
    ImagePicker.launchImageLibrary(photoOptions, (response) => {
      if (response.didCancel) {
        console.log('User cancelled image picker');
      } else if (response.error) {
        _this.props.onReadBarCodeByGalleryFailure && _this.props.onReadBarCodeByGalleryFailure()
      } else if (response.customButton) {
        console.log('User tapped custom button: ', response.customButton);
      } else {
        _this.onBarCodeReadByGalleryStart && _this.onBarCodeReadByGalleryStart()
        readerQR(response.path).then((data) => { // 读取到条码
          console.log({
            data
          });
          _this.props.onBarCodeRead && _this.props.onBarCodeRead({
            data
          })
        }).catch(() => { // 读取失败
          _this.props.onReadBarCodeByGalleryFailure && _this.props.onReadBarCodeByGalleryFailure()
        })
      }
    })
  }

**Comment by appasaheb4** [comment]
change only
readerQR(response.uri).then((data)=>{ // 读取到条码
_this.props.onBarCodeRead && _this.props.onBarCodeRead({data})
}).catch(()=>{ // 读取失败
_this.props.onReadBarCodeByGalleryFailure && _this.props.onReadBarCodeByGalleryFailure()
})

solve!!

**Comment by ztz2** [comment]
Sorry, The repository is no longer maintained
